/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadgrupo5.vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadgrupo5.accesoADatos.AlumnoData;
import universidadgrupo5.accesoADatos.InscripcionData;
import universidadgrupo5.entidades.Alumno;
import universidadgrupo5.entidades.Inscripcion;
import universidadgrupo5.entidades.Materia;

/**
 *
 * @author DANIELALEJANDROMIRAN
 */
public class Actualizar_notas extends javax.swing.JInternalFrame {
    AlumnoData AD = new AlumnoData();
    InscripcionData ID = new InscripcionData();
    DefaultTableModel DTM = new DefaultTableModel();
    /**
     * Creates new form Actualizar_notas
     */
    public Actualizar_notas() {
        initComponents();
        JComboAlumno.removeAllItems();
        for(Alumno alumno:AD.listarAlumnos()){
            JComboAlumno.addItem(alumno);
        }
        DTM.setColumnIdentifiers(new Object[]{"ID","Nombre","nota"});
        if(JComboAlumno.getSelectedIndex()!=-1){
            for(Inscripcion materia:ID.obtenerInscripcionesPorAlumno(((Alumno)JComboAlumno.getItemAt(0)).getIdAlumno())){
                DTM.addRow(new Object[]{materia.getMateria().getIdMateria(),materia.getMateria().getNombre(),materia.getNota()});
            }
        } else{
            JOptionPane.showMessageDialog(this, "no hay alumnos.");
        }
        JTable.setModel(DTM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JComboAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel1.setText("Seleccionar alumno");
        jPanel1.add(jLabel1);

        JComboAlumno.setFont(new java.awt.Font("DialogInput", 0, 10)); // NOI18N
        JComboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(JComboAlumno);

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Materia", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTable);
        if (JTable.getColumnModel().getColumnCount() > 0) {
            JTable.getColumnModel().getColumn(0).setResizable(false);
            JTable.getColumnModel().getColumn(1).setResizable(false);
            JTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setFont(new java.awt.Font("DialogInput", 0, 15)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jLabel2.setText("                                                                                                         ");
        jPanel2.add(jLabel2);

        jButton2.setFont(new java.awt.Font("DialogInput", 0, 15)); // NOI18N
        jButton2.setText("Salir");
        jPanel2.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboAlumnoActionPerformed
        if(JComboAlumno.getSelectedIndex()!=-1){
            
        }
    }//GEN-LAST:event_JComboAlumnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(JTable.getSelectedRow()!=-1 && JComboAlumno.getSelectedIndex()!=-1){
            try{
                Inscripcion inscripcion = ID.obtenerInscripcionesPorAlumno(((Alumno)JComboAlumno.getSelectedItem()).getIdAlumno()).get(JTable.getSelectedRow());
                ID.actualizarNota(inscripcion.getAlumno().getIdAlumno(), inscripcion.getMateria().getIdMateria(), Double.parseDouble((String)DTM.getValueAt(JTable.getSelectedRow(), 2)));
                for(int i=DTM.getRowCount()-1;i>=0;i--){
                DTM.removeRow(i);
                }
                for(Inscripcion materia:ID.obtenerInscripcionesPorAlumno(((Alumno)JComboAlumno.getItemAt(0)).getIdAlumno())){
                DTM.addRow(new Object[]{materia.getMateria().getIdMateria(),materia.getMateria().getNombre(),materia.getNota()});
                }
            }catch(Exception cs){
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "elegir materia a guardar.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> JComboAlumno;
    private javax.swing.JTable JTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
